"""
FILE: backend/knowledge_base.py
PURPOSE: Human-readable text for every finding type: title, description,
recommendation, priority and the likelihood/impact used in the risk matrix.

Keeping text OUT of the scoring code means the engine stays small and the
wording can be reviewed (or localised) without touching any logic.
Priority: IMMEDIATE | IMPORTANT | GOOD PRACTICE
"""
I, M, G = "IMMEDIATE", "IMPORTANT", "GOOD PRACTICE"

# finding_type: (title, description, recommendation, priority, likelihood, impact)
KB = {
 "PUBLIC_PROFILE": ("Profile is publicly visible", "Anyone, including strangers, can view your profile content.",
   "Switch to a friends-only or private profile, or at least restrict what a public profile shows.", M, "HIGH", "MEDIUM"),
 "SEARCH_ENGINE_INDEXING": ("Profile can appear in search engines", "Your profile may be found through web searches without logging in.",
   "Turn off search-engine indexing of your profile in your privacy settings.", M, "MEDIUM", "MEDIUM"),
 "FRIENDS_LIST_VISIBLE": ("Friends / followers list is visible", "Your connections can be seen by people outside your trusted circle.",
   "Limit the friends/followers list to 'only me' or 'friends'.", G, "MEDIUM", "LOW"),
 "CONTACT_LOOKUP_ENABLED": ("Account can be found by phone / email look-up", "Anyone who knows your number or email can locate your account.",
   "Disable 'find me by phone number / email' options.", M, "MEDIUM", "MEDIUM"),
 "USERNAME_REUSE": ("Same username across platforms", "A shared handle lets accounts be correlated across sites.",
   "Use different handles for personal and public/professional accounts.", G, "MEDIUM", "LOW"),
 "PHONE_PUBLIC": ("Phone number reported as publicly visible", "A public phone number supports spam, SIM-swap and impersonation attempts.",
   "Limit phone-number visibility to 'only me' wherever possible.", I, "MEDIUM", "MEDIUM"),
 "EMAIL_PUBLIC": ("Personal email reported as publicly visible", "A public email address is a target for phishing and account-recovery abuse.",
   "Hide your email, or use a separate alias for public profiles.", M, "MEDIUM", "MEDIUM"),
 "BIRTHDAY_PUBLIC": ("Full birth date is publicly visible", "A full birth date is a common identity-verification detail.",
   "Show only day and month, or hide your birth date entirely.", M, "MEDIUM", "MEDIUM"),
 "HOME_INFO_PUBLIC": ("Home-related details are publicly visible", "Home details link your online identity to a physical place.",
   "Remove home address, street and neighbourhood details from your public profile.", I, "MEDIUM", "HIGH"),
 "WORKPLACE_PUBLIC": ("Workplace is publicly visible", "Employer information makes targeted phishing more believable.",
   "Show workplace to connections only, or keep it generic.", G, "MEDIUM", "MEDIUM"),
 "EDUCATION_PUBLIC": ("Education is publicly visible", "School or college details add context usable in scams.",
   "Restrict education details to connections.", G, "LOW", "LOW"),
 "FAMILY_INFO_PUBLIC": ("Family / relationship details are public", "Family details help impersonators and security-question guessers.",
   "Hide relationship status and family links from the public.", G, "MEDIUM", "MEDIUM"),
 "PROFILE_LOCATION_PUBLIC": ("Location shown on public profile", "A visible city narrows searches about you.",
   "Use a region-level location or remove it from your profile.", G, "MEDIUM", "LOW"),
 "REALTIME_LOCATION": ("Real-time location sharing enabled", "Live location tells viewers exactly where you are right now.",
   "Avoid publicly broadcasting real-time location unless intentionally needed; share live location only with specific trusted people.", I, "MEDIUM", "HIGH"),
 "LOCATION_TAGGING": ("Posts carry location tags", "Geotags build a map of the places you visit.",
   "Turn off location tagging by default and remove tags from sensitive posts.", M, "MEDIUM", "MEDIUM"),
 "LIVE_CHECKINS": ("Live check-ins while at a place", "Live check-ins reveal when you are at (or away from) a location.",
   "Avoid check-ins at home, work or school; post about a place after you have left.", M, "MEDIUM", "HIGH"),
 "TRAVEL_POSTS": ("Travel plans posted before / during trips", "Advance travel posts reveal when you will be away from home.",
   "Share travel photos after you return and limit the audience.", M, "MEDIUM", "HIGH"),
 "ROUTINE_PATTERNS": ("Posts reveal routines", "Repeated places and times make your movements predictable.",
   "Vary or delay posts that show regular places and times.", G, "MEDIUM", "MEDIUM"),
 "PUBLIC_POSTS": ("Posts are publicly visible by default", "Everything you post reaches the public unless changed per post.",
   "Set the default post audience to friends or private.", M, "HIGH", "MEDIUM"),
 "SENSITIVE_PHOTO_CONTENT": ("Photos show badges, documents or plates", "Photo backgrounds can leak details you did not type.",
   "Crop or blur badges, documents, screens, boarding passes and plates; delete past posts that show them.", I, "MEDIUM", "HIGH"),
 "FAMILY_PHOTOS_PUBLIC": ("Public photos of children / family", "Photos of minors and relatives are shared without their consent and can be reused.",
   "Share family photos only with a small trusted audience; avoid faces, uniforms and school names.", I, "MEDIUM", "HIGH"),
 "PUBLIC_STORIES": ("Stories / reels visible outside connections", "Short-lived content is still visible and can be captured.",
   "Limit stories and highlights to close friends or connections.", G, "MEDIUM", "LOW"),
 "OPEN_REQUESTS": ("Anyone can send connection requests", "Open requests make it easy for strangers and fake accounts to reach you.",
   "Restrict requests to friends of friends or require approval.", G, "HIGH", "LOW"),
 "UNKNOWN_CONNECTIONS": ("Unknown connection requests accepted", "Accepting strangers gives them access to friends-only content and trust.",
   "Verify unfamiliar profiles (mutual contacts, account age, activity) before accepting, or decline.", I, "HIGH", "MEDIUM"),
 "CONNECTIONS_NOT_REVIEWED": ("Connections not reviewed recently", "Unfamiliar or fake connections may have accumulated.",
   "Review and remove unfamiliar friends or followers every few months.", G, "MEDIUM", "LOW"),
 "NO_AUDIENCE_SEGMENTATION": ("No close-friends / restricted lists used", "Personal posts reach a larger audience than necessary.",
   "Create a close-friends list for personal updates.", G, "MEDIUM", "LOW"),
 "TAG_REVIEW_DISABLED": ("Tag review is disabled", "Others can attach your name to posts that appear on your profile unreviewed.",
   "Enable tag review so tags need your approval first.", M, "MEDIUM", "MEDIUM"),
 "ANYONE_CAN_TAG": ("Anyone can tag you", "People outside your circle can associate your identity with their content.",
   "Limit tagging to friends or no one.", M, "MEDIUM", "MEDIUM"),
 "AUTO_TAGGED_POSTS": ("Tagged posts appear automatically", "Other people's posts can show up on your profile without approval.",
   "Require approval before tagged posts appear on your profile.", G, "MEDIUM", "LOW"),
 "OPEN_MENTIONS": ("Anyone can mention you", "Open mentions are a channel for harassment and scam outreach.",
   "Restrict who can mention or message you.", G, "MEDIUM", "LOW"),
 "MFA_DISABLED": ("Multi-factor authentication is disabled", "Without MFA, a stolen or guessed password is enough to take over the account.",
   "Enable multi-factor authentication using the strongest supported method available.", I, "MEDIUM", "HIGH"),
 "WEAK_MFA_METHOD": ("MFA method is weak or unknown", "SMS codes can be intercepted or SIM-swapped; an unknown method is unverified.",
   "Switch to an authenticator app or a hardware security key.", M, "MEDIUM", "MEDIUM"),
 "PASSWORD_REUSE": ("Password reuse reported", "A breach on another site could expose this account.",
   "Set a unique, long password for this account and every other account.", I, "HIGH", "HIGH"),
 "NO_PASSWORD_MANAGER": ("No password manager in use", "Unique strong passwords are hard to maintain without a manager.",
   "Adopt a reputable password manager and let it generate passwords.", M, "MEDIUM", "MEDIUM"),
 "LOGIN_ALERTS_DISABLED": ("Login alerts are disabled", "You would not be warned about sign-ins from new devices.",
   "Enable login alerts where available.", M, "MEDIUM", "MEDIUM"),
 "SESSIONS_NOT_REVIEWED": ("Active sessions not reviewed", "Old or unknown sessions may remain signed in.",
   "Review active sessions and sign out of devices you do not recognise.", M, "MEDIUM", "MEDIUM"),
 "RECOVERY_NOT_REVIEWED": ("Recovery information not reviewed", "Outdated recovery email or phone is a takeover route.",
   "Confirm your recovery email and phone are current and protected by MFA.", M, "MEDIUM", "HIGH"),
 "DEVICES_NOT_CHECKED": ("Unknown devices not checked", "Unfamiliar logins may go unnoticed.",
   "Check the 'where you are logged in' page regularly.", G, "MEDIUM", "MEDIUM"),
 "APPS_NOT_REVIEWED": ("Third-party apps not reviewed", "Connected apps may hold access you no longer need.",
   "Regularly review and revoke unnecessary application access (principle of least privilege).", M, "MEDIUM", "MEDIUM"),
 "UNUSED_APPS_REMAIN": ("Unused connected apps remain", "Unused integrations are unnecessary access.",
   "Remove apps and games you no longer use.", M, "MEDIUM", "MEDIUM"),
 "PERMISSIONS_UNCHECKED": ("App permissions not checked", "Apps may be granted more access than they need.",
   "Read the permission list before connecting; grant only what is required.", G, "MEDIUM", "MEDIUM"),
 "SOCIAL_LOGIN_OVERUSE": ("Heavy use of 'Sign in with social account'", "Each connection links another site to your profile.",
   "Use social login only for trusted services; prefer unique credentials otherwise.", G, "MEDIUM", "LOW"),
 "RESPONDS_TO_SUSPICIOUS_DMS": ("Replies to suspicious messages", "Replying to unsolicited offers invites follow-up scams.",
   "Do not reply to unexpected offers; report and block the sender.", I, "HIGH", "MEDIUM"),
 "LOW_LINK_AWARENESS": ("Low confidence spotting scam links", "Limited awareness raises phishing susceptibility.",
   "Learn the signs of phishing: urgency, odd domains, unexpected requests. Review the awareness guide.", M, "MEDIUM", "MEDIUM"),
 "CLICKS_UNEXPECTED_LINKS": ("Clicks unexpected links without checking", "Hijacked friend accounts commonly spread phishing links.",
   "Be cautious with unexpected links; confirm with the sender through another channel.", I, "HIGH", "HIGH"),
 "SHARES_VERIFICATION_CODES": ("Verification codes shared on request", "Anyone holding your code can usually complete a login as you.",
   "Never share verification codes. No legitimate service asks for them by message.", I, "MEDIUM", "HIGH"),
 "NO_IMPERSONATION_CHECK": ("No verification of urgent requests from friends", "Impersonation scams exploit trust in a familiar name.",
   "Verify urgent requests for money or help by phone or in person.", M, "HIGH", "MEDIUM"),
 "SUSPICIOUS_GIVEAWAYS": ("Joins giveaways asking for logins or forms", "Fake giveaways harvest credentials and personal data.",
   "Avoid giveaways that ask you to log in or share personal details.", G, "MEDIUM", "MEDIUM"),
 "OLD_POSTS_NOT_REVIEWED": ("Old public posts not reviewed", "Historical posts can still expose outdated or sensitive details.",
   "Review old public posts and photos; delete or restrict anything sensitive.", M, "MEDIUM", "MEDIUM"),
 "SETTINGS_NOT_REVIEWED": ("Privacy settings not reviewed recently", "Defaults and features change, so settings drift.",
   "Schedule a privacy check-up every few months.", M, "HIGH", "MEDIUM"),
 "UNUSED_ACCOUNTS": ("Old or unused accounts still active", "Forgotten accounts are rarely protected.",
   "Delete accounts you no longer use.", G, "MEDIUM", "MEDIUM"),
 "PHOTO_METADATA_UNMANAGED": ("Photo metadata not managed", "Photos can carry device, time and sometimes GPS metadata.",
   "Disable location in your camera app or strip metadata before posting (see the Metadata Viewer tool).", G, "MEDIUM", "MEDIUM"),
 "PUBLIC_COMMENTS_OVERSHARING": ("Personal details in public comments", "Public comments are part of your active digital footprint.",
   "Avoid sharing school, workplace or plans in public comments.", G, "MEDIUM", "LOW"),
}

PRIORITY_ORDER = {"IMMEDIATE": 0, "IMPORTANT": 1, "GOOD PRACTICE": 2}


def kb(finding_type: str) -> dict:
    t = KB[finding_type]
    return {"finding_type": finding_type, "title": t[0], "description": t[1],
            "recommendation": t[2], "priority": t[3], "likelihood": t[4], "impact": t[5]}


# 18-item printable checklist from the project brief (category tags help the UI).
CHECKLIST = [
 ("Review profile visibility", "profile"), ("Hide unnecessary contact information", "personal_info"),
 ("Review birth-date visibility", "personal_info"), ("Review location sharing", "location"),
 ("Avoid unnecessary real-time location posts", "location"), ("Review tagging permissions", "tagging"),
 ("Review followers / friends", "connections"), ("Verify unfamiliar requests", "connections"),
 ("Enable MFA", "account_security"), ("Enable login alerts where available", "account_security"),
 ("Review active sessions", "account_security"), ("Review connected apps", "third_party"),
 ("Remove unused integrations", "third_party"), ("Review old public posts", "footprint"),
 ("Review photo privacy", "content"), ("Be cautious with unexpected links", "social_engineering"),
 ("Never share verification codes", "social_engineering"), ("Review privacy settings periodically", "footprint"),
]

AWARENESS_TIPS = [
 "Strong account security is not the same as strong privacy: a locked-down account can still overshare.",
 "Post about a place after you leave it, not while you are there.",
 "Nobody legitimate will ever ask you to read out a verification code.",
 "Other people's posts can expose you. Turn on tag review.",
 "Public details such as employer and school make scam messages more believable.",
 "Review connected apps twice a year and remove what you do not use.",
]
