"""Run:  python -m tests.run_test_report   ->  writes docs/TEST_REPORT.md (real Actual Result column)."""
from pathlib import Path

from .test_cases import CASES

rows, passed = [], 0
for c in CASES:
    ok, actual = c["run"]()
    passed += ok
    rows.append(f"| {c['id']} | {c['scenario']} | {c['input']} | {c['expected']} | {str(actual).replace('|', '/')} | {'PASS' if ok else 'FAIL'} |")
out = Path(__file__).resolve().parent.parent / "docs" / "TEST_REPORT.md"
out.write_text("# Test Report\n\nGenerated by `python -m tests.run_test_report` from the live scoring engine.\n\n"
               f"**Result: {passed}/{len(CASES)} documented scenarios passed.** Additional privacy/security tests live in `tests/test_privacy_security.py` (see docs/SECURITY_PRIVACY_TESTING.md).\n\n"
               "| Test ID | Scenario | Input | Expected Result | Actual Result | Pass/Fail |\n|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n", encoding="utf-8")
print(f"{passed}/{len(CASES)} passed -> {out}")
